package jtree;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Frank Haver
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOnderdeel = new javax.swing.JLabel();
        tfOnderdeel = new javax.swing.JTextField();
        btnAddOnderdeel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boomMcDonalds = new javax.swing.JTree();
        btnVerwijderNode = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOnderdeel.setText("Onderdeel:");

        tfOnderdeel.setName("tfOnderdeel"); // NOI18N

        btnAddOnderdeel.setText(">>");
        btnAddOnderdeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOnderdeelActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("McDonalds");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Eten");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Personeel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Interieur");
        treeNode1.add(treeNode2);
        boomMcDonalds.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(boomMcDonalds);

        btnVerwijderNode.setText("X");
        btnVerwijderNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderNodeActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setName("lblError"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOnderdeel)
                        .addGap(18, 18, 18)
                        .addComponent(tfOnderdeel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddOnderdeel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnVerwijderNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOnderdeel)
                            .addComponent(tfOnderdeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddOnderdeel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerwijderNode)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(lblError)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerwijderNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderNodeActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        DefaultTreeModel model = (DefaultTreeModel) boomMcDonalds.getModel();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) boomMcDonalds.getLastSelectedPathComponent();
        if (selectedNode != null) {
            if (selectedNode.isRoot()) {
                lblError.setText("Je kan de McDonalds niet zomaar verwijderen, OEN!");
            }
            else{
                model.removeNodeFromParent(selectedNode);
            }

        } else {
            lblError.setText("Kies een onderdeel om te verwijderen");
        }

    }//GEN-LAST:event_btnVerwijderNodeActionPerformed

    private void btnAddOnderdeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOnderdeelActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        DefaultTreeModel model = (DefaultTreeModel) boomMcDonalds.getModel();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) boomMcDonalds.getLastSelectedPathComponent();
        DefaultMutableTreeNode newCity = new DefaultMutableTreeNode(tfOnderdeel.getText());
        if (selectedNode != null) {
            if (!tfOnderdeel.getText().trim().equals("")) {
                model.insertNodeInto(newCity, selectedNode, selectedNode.getChildCount());
            } else {
                lblError.setText("Vul een onderdeel in");
            }
        } else {
            lblError.setText("Je moet een onderdeel selecteren om er iets aan toe te voegen");
        }
    }//GEN-LAST:event_btnAddOnderdeelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree boomMcDonalds;
    private javax.swing.JButton btnAddOnderdeel;
    private javax.swing.JButton btnVerwijderNode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblOnderdeel;
    private javax.swing.JTextField tfOnderdeel;
    // End of variables declaration//GEN-END:variables
}
